apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bulletin-board-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: notas.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: bulletin-board-service
                port:
                  number: 80
